FROM golang:1.25.5-trixie AS builder

RUN apt-get update && apt-get install -y git gcc musl-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /build

COPY go.mod go.sum ./
COPY third_party/ ./third_party/
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o amf ./cmd/

FROM alpine:3.15

LABEL description="Free5GC open source 5G Core Network - AMF" \
    version="Stage 3"

ENV F5GC_MODULE=amf

RUN apk add --no-cache tini

WORKDIR /free5gc
RUN mkdir -p config/ log/ cert/

COPY --from=builder /build/amf ./
COPY amf.pem ./cert/
COPY amf.key ./cert/
COPY amfcfg.yaml ./config/

VOLUME [ "/free5gc/config" ]
VOLUME [ "/free5gc/cert" ]

EXPOSE 8000

ENTRYPOINT [ "/sbin/tini", "--" ]
CMD [ "./amf" ]